name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: MatheusASilva
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "your-username"
          author_email: "your-email@example.com"
          message: "Update Snake animation"
          add: "dist/github-contribution-grid-snake.svg"
